/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisPanel: typeof import('./components/kanban/AnalysisPanel.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    BidFormModal: typeof import('./components/kanban/BidFormModal.vue')['default']
    BoardColumn: typeof import('./components/kanban/BoardColumn.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FilterBar: typeof import('./components/kanban/FilterBar.vue')['default']
    LoginGate: typeof import('./components/layout/LoginGate.vue')['default']
    ProjectMultiSelect: typeof import('./components/kanban/ProjectMultiSelect.vue')['default']
    RingChart: typeof import('./components/kanban/RingChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCard: typeof import('./components/kanban/TaskCard.vue')['default']
    TaskDrawer: typeof import('./components/kanban/TaskDrawer.vue')['default']
    TaskFormModal: typeof import('./components/kanban/TaskFormModal.vue')['default']
    TodoNotice: typeof import('./components/layout/TodoNotice.vue')['default']
  }
}
